#! /bin/sh

if ! pgrep sxhkd > /dev/null
then
  sxhkd &
fi
setxkbmap -option caps:escape
feh --bg-fill Pictures/wallpaper-781505.jpg

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
