#!/bin/sh
if ! pgrep sxhkd > /dev/null; then
  export SXHKD_SHELL=/bin/sh
  sxhkd &
fi
if ! pgrep xss-lock > /dev/null; then
  xss-lock -- dm-tool lock &
fi
if ! tmux info > /dev/null; then
  tmux start-server &
fi

function arrange_monitors () {
  if [ "$(bspc query -M | wc -l)" -eq "3" ]; then
    bspc monitor $(bspc query -M | sed -n 1p) -d I II III
    bspc monitor $(bspc query -M | sed -n 2p) -d IV V VI
    bspc monitor $(bspc query -M | sed -n 3p) -d VII VIII
  elif [ "$(bspc query -M | wc -l)" -eq "2" ]; then
    bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV
    bspc monitor $(bspc query -M | sed -n 2p) -d V VI VII VIII
  else
    bspc monitor -d I II III IV
  fi
}

# Remember to set to your wallpaper
function set_wallpaper () {
  # feh --bg-fill ~/Pictures/glacier-869593_1920.jpg
  return 0
}

bspc config border_width                2
bspc config window_gap                  12
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config click_to_focus              true
bspc monitor -d                         I II III IV

source ~/.scripts/bootstrap.sh
# Remember to change to your primary screen
# scrn primary LVDS1
scrn off 2> /dev/null
kbdl 0 2>/dev/null
set_wallpaper

if [ "$(btt has_battery)" ]; then
  pid=$(pgrep bspwmrc | grep -v $$)
  if [ "$pid" ]; then kill $pid 2>/dev/null; fi
  while :; do
    if [ "$(btt status)" != "Charging" ] && (($(btt capacity) < 11)); then
      ntf "btt format"
    fi
    sleep 120
  done &
fi

bspc subscribe monitor_add | while read -r line; do
  arrange_monitors
  set_wallpaper
done &

bspc subscribe monitor_remove | while read -r line; do
  arrange_monitors
  set_wallpaper
done &

bspc subscribe monitor_geometry | while read -r line; do
  set_wallpaper
done &
