#! /bin/sh
if ! pgrep sxhkd > /dev/null; then
  sxhkd &
fi
if ! pgrep xss-lock > /dev/null; then
  xss-lock -- dm-tool lock &
fi
~/.scripts/kbdl.sh 0
feh --bg-center Pictures/5KxJD9H.png

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config click_to_focus              true

primary_monitor=$(~/.scripts/scrn.sh get_primary)
secondary_monitor=$(~/.scripts/scrn.sh get_secondary)
bspc monitor $primary_monitor -d I II III IV
if [[ $secondary_monitor ]]; then
  bspc monitor $secondary_monitor -d V VI VII VIII
fi
