#!/bin/sh
if ! pgrep sxhkd > /dev/null; then
  sxhkd &
fi
if ! pgrep xss-lock > /dev/null; then
  xss-lock -- dm-tool lock &
fi

kbdl=~/.scripts/kbdl.sh
if [[ $($kbdl 2>/dev/null) ]]; then $kbdl 0; fi
# Set wallpaper
# feh --bg-fill Pictures/wallpaper.jpg

if [[ -e $(ls /sys/class/power_supply) ]]; then
  pid=$(pgrep bspwmrc | grep -v $$)
  if [[ $pid ]]; then kill $pid 2>/dev/null; fi
  while :; do
    battery_level=$(cat /sys/class/power_supply/BAT0/capacity)
    if [[ $battery_level -le 10 ]]; then
      ~/.scripts/ntf.sh btt
    fi
    sleep 120
  done &
fi

bspc config border_width                2
bspc config window_gap                  12
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config click_to_focus              true

primary_monitor=$(~/.scripts/scrn.sh get_primary)
secondary_monitor=$(~/.scripts/scrn.sh get_secondary)
bspc monitor $primary_monitor -d I II III IV
if [[ $secondary_monitor ]]; then
  bspc monitor $secondary_monitor -d V VI VII VIII
fi
