#!/bin/sh
width=120
height=20
x=1236
y=10
background=#1e2127
foreground=#9ba2b3
options="-g ${width}x${height}+${x}+${y} -B ${background} -F ${foreground}"
message=$1

if pgrep lemonbar > /dev/null; then
  pkill lemonbar
fi

(echo "%{c} ${message}"; sleep 5) | lemonbar ${options}
