(global-auto-complete-mode t)
(ido-mode t)
(ido-vertical-mode t)
(flx-ido-mode t)
(projectile-global-mode)
(evil-commentary-mode)
(global-evil-leader-mode)
(dtrt-indent-mode t)
(electric-pair-mode t)
(evil-jumper-mode t)
(evil-mode t)
(global-auto-revert-mode t)
(global-evil-surround-mode t)
(global-evil-visualstar-mode t)
(global-git-gutter-mode t)
(global-hl-line-mode t)
(helm-autoresize-mode t)
(show-paren-mode t)
